export const projects = [
  {
    id: 'content-engine', number: '01', title: 'Content Engine', kind: 'Agent systems', status: 'Complete — demo mode verified',
    summary: 'A 48-node LangGraph agent that retrieves brand memory, pauses for a real human review gate, revises with feedback, and tracks its own cost and reliability.',
    stack: ['Python', 'LangGraph', 'Supabase / pgvector', 'FastAPI', 'LangSmith'],
    lead: 'From a client interview to a reviewable content package, with brand memory at every generation step and a review loop that actually closes.',
    challenge: 'Content operations involve more than generating text. Brand context needs to persist per client, a reviewer needs to change one piece without restarting everything, and someone eventually has to trust the thing runs unattended.',
    approach: 'I moved a custom DAG executor to LangGraph, preserving an offline demo path against fixture data. Brand documents are chunked, embedded, and retrieved per tenant. Human review uses a real checkpointed interrupt/resume — a "changes requested" decision routes back into just that content node with the reviewer’s words folded into its prompt, re-publishes to Notion, and re-notifies Slack before pausing for a second look. Generated pieces are scored by an LLM-as-judge tone check, every node execution can trace to LangSmith, and a cost tracker meters real per-call spend against published Anthropic/Gemini pricing. 109 unit and integration tests currently pass.',
    evidence: ['Client-scoped brand retrieval with Supabase and pgvector — see the real retrieved passages below.', 'A full changes-requested → revision → re-review cycle, walked end-to-end and captured from an actual run.', 'Checkpointing, retries, idempotent webhooks, failed-run recording, and cost tracking, each cited to its own test.'],
    tradeoff: 'Feedback changes what the system retrieves and includes in its prompts; it does not fine-tune the language model. The demo’s mock text provider replies with the same fixture regardless of prompt, so the revision demo below shows the real mechanism without genuinely different text — live mode calls the real API and would. The FastAPI service and Railway config exist and are tested, but a live deployment has not been independently verified from this portfolio.',
    repo: 'https://github.com/ahmadsmadi-oss/content-engine',
    sourceNote: 'Architecture and test results checked against the local source, its README, and its own test suite. Deployment is configured but not independently verified live from this portfolio build.',
  },
  {
    id: 'pitch-vision', number: '02', title: 'Football Match Analytics', kind: 'Computer vision → full stack', status: 'Working local demo',
    summary: 'Football footage becomes tracked movement, player analytics, and a tactical view of shape, pressure, space, and phase of play.',
    stack: ['YOLO', 'OpenCV', 'SciPy', 'React', 'Node.js'],
    lead: 'A match-analytics platform that connects a computer-vision pipeline to an interface you can explore.',
    challenge: 'A moving broadcast camera makes identity tracking and physical measurement two different problems. Missed detections, kit colors, calibration, and short track lifespans all affect the analytics downstream.',
    approach: 'I fine-tuned separate models for broadcast and overhead views, fused the useful detections, used ByteTrack for short-term continuity, and registered a moving tactical camera to a 105 × 68 m pitch. Calibrated positions feed heatmaps, an explainable activity rating, formation graphs, phase labels, block estimates, pressure checks, passing-lane geometry, and a Node and React explorer.',
    evidence: ['Explore a real five-minute Liverpool versus Real Madrid sample with lineup-seeded identities, heatmaps, and measured rating inputs.', 'Scrub the synchronized match replay with team shape, space ownership, and passing-lane overlays.', 'Review detected pressure and lateral movement moments with the measurement behind each suggestion.'],
    tradeoff: 'This is a five-minute visible-sample assessment, not a full-match grade. Same-team player names are formation-seeded and remain provisional until jersey-number anchors are reviewed. Possession, block labels, pressure, and coaching suggestions are transparent heuristics, and missing observations stay visible in the interface.',
    sourceNote: 'The base tracking pattern builds on a football-analysis tutorial. The measurement filtering, analytics, top-view tactical pipeline, validation, and full-stack platform are the project’s additions. AWS deployment is prepared and remains unverified.',
  },
  {
    id: 'coordinate-classifier', number: '03', title: 'Coordinate Classification', kind: 'Applied machine learning', status: 'Complete',
    summary: 'Comparing classical models and a stacked ensemble for multiclass prediction from spatial coordinates.',
    stack: ['scikit-learn', 'Python', 'Model evaluation'],
    lead: 'A reproducible comparison of five classification approaches, from linear baselines to an ensemble.',
    challenge: 'Given three coordinate features, predict a discrete process step. The useful question is which model performs well under a consistent evaluation procedure, and whether extra complexity earns its place.',
    approach: 'I compared logistic regression, SVC, random forest, and decision tree models, with stratified five-fold cross-validation for hyperparameter search. A random-forest and SVC stack uses logistic regression as its final estimator. The trained models are serialized with joblib.',
    evidence: ['0.9961 weighted F1 in the repository’s evaluation results.', 'A stratified 70/30 train/test split.', 'Random forest, decision tree, and the stacked model tied in the recorded results.'],
    tradeoff: 'These results describe this dataset and split. The final model choice also used the test-set comparison, so a new untouched holdout would be needed for an unbiased final selection estimate.',
    repo: 'https://github.com/ahmadsmadi-oss/AER850_Project_1',
    sourceNote: 'Metric and procedure verified against model_results.csv and project1.py.',
  },
  {
    id: 'visual-inspection', number: '04', title: 'Aircraft Surface Inspection', kind: 'Deep learning', status: 'Complete',
    summary: 'Convolutional models that classify aircraft-surface defects from images.',
    stack: ['TensorFlow', 'Keras', 'Image classification'],
    lead: 'An image-classification pipeline for cracks, missing screw heads, and paint degradation.',
    challenge: 'Visual inspection depends on subtle local features. A useful model needs to learn those signals while generalizing beyond the exact images it sees during training.',
    approach: 'I compared CNN architectures using image augmentation, regularization, and a learning-rate schedule. Training and validation histories make the effects of each change visible instead of relying on one headline score.',
    evidence: ['Three defect categories.', 'Baseline and revised CNN architectures.', 'Saved training histories and accuracy/loss curves.'],
    tradeoff: 'This is a defect-classification prototype. It is not an aircraft maintenance certification tool or a substitute for an inspection decision.',
    repo: 'https://github.com/ahmadsmadi-oss/AER850_Project_2',
    sourceNote: 'Implementation checked against the repository’s training scripts and saved outputs.',
  },
  {
    id: 'component-detection', number: '05', title: 'PCB Component Detection', kind: 'Computer vision', status: 'Complete',
    summary: 'OpenCV preprocessing and YOLO detection for components on printed circuit boards.',
    stack: ['YOLO11', 'OpenCV', 'Object detection'],
    lead: 'Finding and classifying components across different board layouts.',
    challenge: 'Different circuit boards change the arrangement, scale, and appearance of components. Detection needs to be checked on layouts beyond the training examples.',
    approach: 'I combined image preprocessing and masking with an Ultralytics YOLO11 workflow for 13 component classes. The project includes checks on Arduino Uno, Arduino Mega, and Raspberry Pi boards.',
    evidence: ['Thirteen component classes.', 'Preprocessing and masking in OpenCV.', 'Generalization checks across three unseen board layouts.'],
    tradeoff: 'A handful of unseen boards is a qualitative generalization check, not a broad production benchmark. The portfolio does not imply production deployment.',
    repo: 'https://github.com/ahmadsmadi-oss/AER850_Project_3',
    sourceNote: 'Project scope supplied by Ahmad; preprocessing checked against masking.py.',
  },
];
