import {useEffect,useRef,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {ArrowLeft,Play,Pause,ArrowRight,Eye,Activity} from 'lucide-react';
import {useData,useVideoAvailable,PitchLines} from './PitchPrimitives';
import LiquidGlass from './LiquidGlass';
const fmt=(v,n=1)=>Number.isFinite(v)?v.toFixed(n):'—';
const fallbackColors={1:'#f4eee0',2:'#55b4e5'};
const shortName=name=>name?.split(' ').at(-1)??'Player';
function ActivityHeatmap({positions=[]}){
 const sample=positions.length>420?positions.filter((_,i)=>i%Math.ceil(positions.length/420)===0):positions;
 return <div className="lab-heatmap"><svg viewBox="0 0 105 68" aria-label="Player position heatmap"><defs><filter id="activity-blur"><feGaussianBlur stdDeviation="2.7"/></filter></defs><rect width="105" height="68" fill="#edf1e9"/><g color="#74817155"><PitchLines/></g><g filter="url(#activity-blur)">{sample.map((point,i)=><circle key={i} cx={point[0]} cy={point[1]} r="3.8" fill="#e8a736" opacity=".16"/>)}</g>{sample.map((point,i)=><circle key={`c${i}`} cx={point[0]} cy={point[1]} r=".42" fill="#bb4c31" opacity=".2"/>)}</svg></div>
}
export default function TacticalLab(){
 const {id}=useParams();const {data,loading,error}=useData(`/tactics/${encodeURIComponent(id)}.json`);
 const videoSrc=`/tactics/${id}/video.mp4`;const videoAvailable=useVideoAvailable(videoSrc);
 const [index,setIndex]=useState(0),[playing,setPlaying]=useState(false),[team,setTeam]=useState(1),[space,setSpace]=useState(false),[links,setLinks]=useState(true),[lanes,setLanes]=useState(false),[selected,setSelected]=useState(null),[filter,setFilter]=useState('all');
 const video=useRef(null),initialised=useRef(null);
 useEffect(()=>{setIndex(0);setPlaying(false);setSelected(null)},[id]);
 useEffect(()=>{
  const sourceKey=data?.clip?`${id}:${data.clip}`:null;
  if(!data?.frames?.length||!sourceKey||initialised.current===sourceKey)return;
  const meaningful=data.frames.findIndex(f=>f.players.length>=16&&f.possessionTeam&&f.advice?.some(a=>a.kind!=='quality'));
  setIndex(meaningful>=0?meaningful:0);initialised.current=sourceKey;
 },[data,id]);
 if(loading||error)return <main className="wrap empty-state"><h1>{loading?'Loading the tactical lab…':'Tactical data unavailable'}</h1>{error&&<p>{error}</p>}<Link to="/#work">Return to selected work</Link></main>;
 if(!data.frames?.length)return <main className="wrap empty-state"><h1>No calibrated observations yet.</h1></main>;
 const teams=data.teams?.length?data.teams:[{id:1,name:'Team 1',color:fallbackColors[1],attacks:1},{id:2,name:'Team 2',color:fallbackColors[2],attacks:-1}];
 const teamById=Object.fromEntries(teams.map(item=>[item.id,item]));
 const colors=Object.fromEntries(teams.map(item=>[item.id,item.color||fallbackColors[item.id]]));
 const frame=data.frames[Math.min(index,data.frames.length-1)],shape=frame.shapes[String(team)];
 const seek=i=>{setIndex(i);if(video.current)video.current.currentTime=data.frames[i].time;};
 const toggle=()=>{if(!video.current)return;if(playing)video.current.pause();else video.current.play().catch(()=>setPlaying(false));};
 const reaction=frame.reactions?.[String(team)];
 const player=frame.players.find(p=>p.id===selected),assignment=data.teamAssignments?.[selected],rating=data.ratings?.[selected];
 const adviceFor=(item,sourceFrame)=>item.advice.filter(a=>a.kind===(sourceFrame.possessionTeam===team?'attack':'defend'));
 let suggestions=adviceFor(frame,frame);
 if(!suggestions.length){
  for(let cursor=index-1;cursor>=0;cursor--){const found=adviceFor(data.frames[cursor],data.frames[cursor]);if(found.length){suggestions=found.map(item=>({...item,carriedFrom:data.frames[cursor].time}));break}}
 }
 if(!suggestions.length)suggestions=frame.advice.filter(a=>a.kind==='quality');
 const events=data.events.filter(e=>filter==='all'||e.type===filter);
 const byId=Object.fromEntries(frame.players.map(p=>[p.id,p]));
 const visibleById=new Map(frame.players.map(p=>[p.id,p]));
 for(let cursor=index-1;cursor>=Math.max(0,index-15);cursor--){for(const p of data.frames[cursor].players){if(!visibleById.has(p.id))visibleById.set(p.id,{...p,held:true,heldSeconds:frame.time-data.frames[cursor].time})}}
 const displayPlayers=[...visibleById.values()];
 const roster=Object.entries(data.ratings||{}).map(([playerId,value])=>({id:playerId,...value}));
 const choosePlayer=playerId=>{setSelected(playerId);const visible=data.frames.findIndex(item=>item.players.some(p=>p.id===playerId));if(visible>=0)seek(visible)};
 return <main className="wrap tactical-lab"><div className="match-topline"><Link to="/#work" className="back-link"><ArrowLeft size={16}/> Selected work</Link><span className="lab-status"><i/>TACTICAL ANALYSIS</span></div>
  <header className="lab-heading"><div><span className="eyebrow">FOOTBALL / TACTICAL INTELLIGENCE</span><h1>Read the game.<br/><em>Follow the movement.</em></h1></div><p>A coach’s-eye view of shape, pressure and space. Every dot starts with a detection in the footage.</p></header>
  <div className="lab-source"><span><Eye size={15}/>{data.fixture||teams.map(item=>item.name).join(' vs ')} · {fmt(data.duration)} s</span><span>{data.source||'YOLO tracking pipeline'} · {fmt(data.summary.ballCoverage*100,0)}% retained ball path</span></div>
  {data.validation&&<section className="lab-quality" aria-label="Pipeline validation"><div><small>Player recall</small><strong>{fmt(data.validation.playerRecall35px*100,1)}%</strong></div><div><small>Player precision</small><strong>{fmt(data.validation.playerPrecision35px*100,1)}%</strong></div><div><small>Assigned-team accuracy</small><strong>{fmt(data.validation.teamAccuracy*100,1)}%</strong></div><div><small>Retained ball within 1 m</small><strong>{fmt(data.validation.ballWithin1m*100,0)}%</strong></div><p>Evaluated against matching SoccerTrack annotations. Ground truth is used for this audit only, never as inference input.</p></section>}
  <div className="lab-layout"><section className="lab-board-card"><LiquidGlass className="lab-toolbar" borderRadius={14} tintOpacity={.22}><div className="team-switch" aria-label="Analysis perspective">{data.teams.map(t=><button key={t.id} aria-pressed={team===t.id} onClick={()=>setTeam(t.id)}><i style={{background:colors[t.id]}}/>{t.name}</button>)}</div><div className="overlay-switch">{[['Shape',links,setLinks],['Space',space,setSpace],['Pass lanes',lanes,setLanes]].map(([name,value,set])=><button key={name} aria-pressed={value} onClick={()=>set(!value)}>{name}</button>)}</div></LiquidGlass>
   <div className="tactical-field"><svg viewBox="-3 -3 111 74" role="group" aria-label={`Measured player positions at ${fmt(frame.time)} seconds`}>
    <defs><marker id="lane-arrow" markerWidth="4" markerHeight="4" refX="3" refY="2" orient="auto"><path d="M0 0L4 2L0 4" fill="#edd484"/></marker></defs>
    <rect x="0" y="0" width="105" height="68" fill="#126849"/>
    {space&&frame.space.map((row,y)=>row.map((t,x)=><rect key={`${x}-${y}`} x={x*105/24} y={y*68/16} width={105/24+.05} height={68/16+.05} fill={colors[t]} opacity=".19"/>))}
    <g color="#ffffff35"><PitchLines/></g>
    {links&&frame.edges.map(([a,b])=>byId[a]&&byId[b]&&<line key={`${a}-${b}`} x1={byId[a].x} y1={byId[a].y} x2={byId[b].x} y2={byId[b].y} stroke={colors[byId[a].team]} opacity=".42" strokeWidth=".32"/>)}
    {lanes&&frame.ball&&frame.lanes.filter(l=>l.open).slice(0,3).map(l=><line key={l.id} x1={frame.ball[0]} y1={frame.ball[1]} x2={l.x} y2={l.y} stroke="#edd484" strokeWidth=".35" strokeDasharray="1 1" markerEnd="url(#lane-arrow)"/>)}
    {space&&frame.openSpace&&<g><circle cx={frame.openSpace.x} cy={frame.openSpace.y} r="4" fill="none" stroke="#ead584" strokeWidth=".3" strokeDasharray="1 1"/><text x={frame.openSpace.x} y={frame.openSpace.y+6} fill="#f7e6a4" fontSize="1.4" textAnchor="middle">OPEN AREA</text></g>}
    {displayPlayers.map(p=>{const pressing=!p.held&&Object.values(frame.shapes).some(s=>s.pressers.some(q=>q.id===p.id));const label=p.name?`${p.number} ${shortName(p.name)}`:p.id;return <g key={p.id} role="button" tabIndex="0" opacity={p.held?.32:1} aria-label={`${p.name||`Track ${p.id}`}, ${teamById[p.team]?.name||'team uncertain'}${p.held?', last observed position':''}`} onClick={()=>setSelected(p.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(p.id)}}} className="tactical-dot"><circle cx={p.x} cy={p.y} r="2.5" fill="transparent"/>{pressing&&<circle cx={p.x} cy={p.y} r="2" fill="none" stroke="#f2b56e" strokeWidth=".4"/>}<circle cx={p.x} cy={p.y} r={selected===p.id?1.45:1.15} fill={colors[p.team]??'#aaa99a'} stroke={p.held?'#d6ddcf':selected===p.id?'#ffd878':'#073e30'} strokeDasharray={p.held?'.5 .45':undefined} strokeWidth=".3"/><text x={p.x} y={p.y+3.2} fill="#e5efe5" textAnchor="middle" fontSize="1.32">{label}</text></g>})}
    {frame.ball&&<circle cx={frame.ball[0]} cy={frame.ball[1]} r=".65" fill="#ffd878" stroke="#543d16" strokeWidth=".2"/>}
   </svg><div className="field-caption"><span>{teams.map(item=>`${item.name} attacks ${item.attacks>0?'→':'←'}`).join(' · ')}</span><span>{frame.players.length} measured · {displayPlayers.length-frame.players.length} recent positions held · {frame.ball?`ball: ${frame.ballSource}`:'ball not located'}</span></div></div>
   <div className="lab-playback"><button onClick={toggle} aria-label={playing?'Pause replay':'Play replay'} className="play-button">{playing?<Pause size={18}/>:<Play size={18}/>}</button><span>{fmt(frame.time)} <small>/ {fmt(data.duration)} s</small></span><input type="range" min="0" max={data.frames.length-1} value={index} onChange={e=>seek(Number(e.target.value))} aria-label="Tactical replay time"/></div>
   <div className="phase-timeline" aria-label="Phase timeline">{data.segments.map((s,i)=><button key={i} style={{flex:s.end-s.start,background:s.label.includes('1')?'#aebfab':s.label.includes('2')?'#63a1be':'#e1e2da'}} onClick={()=>seek(s.frameIndex)} title={`${fmt(s.start)}–${fmt(s.end)} s: ${s.label}`} aria-label={`Jump to ${s.label} at ${fmt(s.start)} seconds`}/>)}</div>
   <div className="timeline-key">{teams.map((item,i)=><span key={item.id}><i style={{background:i===0?'#aebfab':'#63a1be'}}/>{item.name} possession</span>)}<span><i style={{background:'#e1e2da'}}/>Unknown</span></div>
   {selected&&<div className="selected-track"><strong>{rating?`${rating.number} ${rating.name}`:`Track ${selected}`}</strong><span>{player?`${teamById[player.team]?.name||'Unassigned'} · ${player.vx===null?'velocity unavailable':`${fmt(Math.hypot(player.vx,player.vy)*3.6)} km/h estimated now`}`:'Not visible at this timestamp'}{rating?.rating?` · ${fmt(rating.rating)} activity rating`:''}</span><button onClick={()=>setSelected(null)}>Clear</button></div>}
  </section>
  <aside className="tactical-insights"><LiquidGlass className="phase-card" borderRadius={14} tintOpacity={.28}><span className="eyebrow">{teamById[team]?.name?.toUpperCase()} / PHASE OF PLAY</span><h2>{frame.phases[String(team)]}</h2><div className="shape-metrics"><div><small>Block estimate</small><strong>{shape.block}</strong></div><div><small>Unit width</small><strong>{fmt(shape.width)} m</strong></div><div><small>Unit depth</small><strong>{fmt(shape.depth)} m</strong></div><div><small>Measured players</small><strong>{shape.count}</strong></div></div></LiquidGlass>
  <div className="insight-label"><Activity size={15}/><span>WHAT THIS MOMENT SUGGESTS</span></div>{suggestions.map((a,i)=><article className="tactical-advice" key={`${a.title}-${i}`}><span className="advice-kind">{a.carriedFrom!==undefined?`Last measured at ${fmt(a.carriedFrom)} s`:a.kind==='quality'?'Data quality':'Coaching hypothesis'}</span><h3>{a.title}</h3><p>{a.suggestion}</p><details><summary>See the evidence</summary><p>{a.evidence}</p>{a.carriedFrom!==undefined&&<p>This card is intentionally held from the last measured ball state; it is context, not a new claim about the current frame.</p>}</details></article>)}
  {reaction&&<article className="tactical-advice"><span className="advice-kind">Observed response</span><h3>The ball moves {reaction.direction}</h3><p>Over {reaction.duration} s, the ball shifts {Math.abs(reaction.ballShift)} m and the selected unit shifts {Math.abs(reaction.blockShift)} m. {reaction.ratio<0?'The unit moves in the opposite direction.':'This describes this movement only, not a learned tendency.'}</p></article>}
  </aside></div>
  {roster.length>0&&<section className="lab-roster"><div className="panel-heading"><div><span className="eyebrow">VISIBLE ACTIVITY / FIVE-MINUTE SAMPLE</span><h2>Ratings and player movement</h2></div><span>Click a player to inspect their heatmap and tracked contribution</span></div><div className="lab-roster-grid"><div className="lab-rating-list">{roster.map(item=><button key={item.id} aria-pressed={selected===item.id} onClick={()=>choosePlayer(item.id)}><span className="roster-number" style={{borderColor:colors[item.team]}}><img src={`/assets/players/${item.id}.jpg`} alt="" loading="lazy"/></span><span><strong>{item.name}</strong><small>{teamById[item.team]?.shortName||teamById[item.team]?.name} · {item.position} · {fmt(item.observedSeconds,0)} s visible</small></span><b className={`rating ${item.rating>=7.5?'high':item.rating>=6.5?'mid':item.rating?'low':'unrated'}`}>{item.rating?fmt(item.rating):'—'}</b></button>)}</div>{selected&&rating?<article className="lab-player-detail"><div className="lab-player-title"><img src={`/assets/players/${selected}.jpg`} alt=""/><div><span className="eyebrow">{teamById[rating.team]?.name} / #{rating.number}</span><h3>{rating.name}</h3><p>{rating.position} · formation-seeded identity</p></div></div><ActivityHeatmap positions={data.heatmaps?.[selected]}/><div className="lab-stat-grid"><span><small>Distance while visible</small><strong>{fmt(rating.distanceM,0)} m</strong></span><span><small>Peak tracked speed</small><strong>{fmt(rating.peakSpeedKmh)} km/h</strong></span><span><small>High-speed movement</small><strong>{fmt(rating.highSpeedSeconds)} s</strong></span><span><small>Press starts</small><strong>{rating.pressures}</strong></span><span><small>Ball proximity</small><strong>{fmt(rating.ballProximitySeconds)} s</strong></span><span><small>Visible coverage</small><strong>{fmt(rating.visibleRatio*100,0)}%</strong></span></div><p className="fine-print">This is a relative activity score for the visible five-minute sample. It does not claim goals, passes, shots, xG, or a full-match performance grade. Player portraits are supplied by <a href="https://www.thesportsdb.com/" target="_blank" rel="noreferrer">TheSportsDB</a>.</p></article>:<div className="lab-player-empty"><span>Select a player</span><p>The map and measured five-minute activity will appear here.</p></div>}</div></section>}
  <div className="lab-bottom"><section className="lab-video"><div className="panel-heading"><h2>Check it against the footage</h2><span>Synchronised replay</span></div>{videoAvailable?<video ref={video} src={videoSrc} controls playsInline preload="metadata" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onTimeUpdate={e=>{const t=e.currentTarget.currentTime;let i=Math.min(data.frames.length-1,Math.floor(t*data.fps/data.stride));setIndex(i)}}/>:<div className="data-note" role="status"><Eye size={16}/><span>{videoAvailable===null?'Checking for match footage…':'Match footage isn’t published here — redistribution rights for this broadcast clip aren’t confirmed. Everything above (positions, phases, ratings) is the real measured output; the board and replay controls work the same without the video.'}</span></div>}<p className="fine-print">{data.ratings?'Teams combine temporal kit appearance with the supplied lineup. Names are formation-seeded and remain provisional until jersey-number anchors are reviewed.':'Outfield teams are inferred from appearance over time; reviewed goalkeeper overrides are marked.'} The pitch uses assumed 105 × 68 m dimensions and frame-by-frame camera registration.</p></section>
  <section className="event-list"><div className="panel-heading"><h2>Moments to review</h2><select aria-label="Filter tactical events" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All moments</option><option value="press candidate">Press candidates</option><option value="turnover">Turnovers</option><option value="lateral move">Lateral moves</option></select></div>{events.length?events.map((e,i)=><button key={i} onClick={()=>seek(e.frameIndex)}><span>{fmt(e.time)} s</span><div><small>{e.type}</small><strong>{e.title}</strong></div><ArrowRight size={15}/></button>):<p className="fine-print">No confident events of this type in this short excerpt. Missing ball observations can prevent event detection.</p>}</section></div>
  <details className="methodology"><summary>Methods, coverage and interpretation</summary><p>Model-generated player and ball positions. Ball retained in {fmt(data.summary.ballCoverage*100,0)}% of sampled frames; sustained possession assigned in {fmt(data.summary.possessionCoverage*100,0)}%. This short clip cannot establish a team's general tactical tendencies.</p>{Object.entries(data.methodology).map(([key,value])=><p key={key}><strong>{key}: </strong>{value}</p>)}<p>Coaching principles informed by <a href="https://www.fifatrainingcentre.com/en/fwc2022/technical-and-tactical-analysis/controlling-the-game-without-the-ball--the-mid-block-and-compactness.php" target="_blank" rel="noreferrer">FIFA’s block and compactness analysis</a>. Our numerical rules are project heuristics, not FIFA’s official classification model.</p></details>
 </main>
}
