// Real captured output from a demo run of the Content Engine's own LangGraph
// agent (workflows/content_engine.workflow.json, run against north_loam's
// fixture data). Not invented for the portfolio: generated by
// scripts/capture_architecture_data.py, which invokes the graph directly and
// reads specific nodes' actual output out of returned state, and reliability
// facts read straight from engine/cost_tracking.py's pricing constants and
// the workflow's own retry/on_error config. See content-engine's README for
// how this is produced.

export const retrievalExample = {
  tenant: 'north_loam',
  feeds: 'blog_post',
  query: 'brand voice and storytelling examples for long-form writing',
  matches: [
    { source: 'brand_tone', score: 0.138, content: "Write like a soil scientist explaining something she genuinely knows well to a smart friend who doesn't happen to know this specific thing yet. Precise, not stiff — numbers and specifics are the point, but they show up in plain sentences, not a spec sheet." },
    { source: 'brand_dna', score: 0.109, content: "The Sage, with a working-scientist's edge rather than a guru's remove. North Loam's authority doesn't come from taste-making — it comes from Maren's actual field credential and a willingness to publish the unflattering number along with the flattering one." },
  ],
};

export const revisionCycle = {
  feedback: 'Cut the last paragraph, it repeats the intro.',
  targetTitle: 'Blog Post',
  steps: ['Round 1 — paused for review', '"changes requested" on Blog Post', 'content_revision node ran', 'Notion page re-synced', 'Slack re-notified', 'Round 2 — paused again', 'Approved'],
  mockTextIdentical: true,
  verifiedBy: 'tests/test_human_review_loop.py',
};

export const reliabilityFacts = [
  { title: 'Per-run cost tracking', body: 'Every live API call gets metered against real Anthropic/Gemini per-token and per-image pricing and written to cost_report.json.', verifiedBy: 'tests/test_cost_tracking.py' },
  { title: 'Checkpointing survives a redeploy', body: 'Demo and dev checkpoint to SQLite; production checkpoints to Postgres — a paused review round survives a process restart.', verifiedBy: 'tests/test_safety_net.py' },
  { title: 'Retries are deliberate, not default', body: 'Most nodes fail fast (1 attempt, abort). The 4 tone-eval judges override to on_error=continue — a judge hiccup never blocks delivery.', verifiedBy: 'tests/test_safety_net.py' },
  { title: 'Idempotent webhooks', body: 'Notion and Slack webhook deliveries are deduped by event key; a duplicate run_id or concurrent resume is refused, not double-processed.', verifiedBy: 'tests/test_safety_net.py' },
  { title: 'Failed runs are recorded', body: 'A run that exhausts retries is written to a failed_runs table and posts a Slack alert — not just a stack trace nobody reads.', verifiedBy: 'tests/test_safety_net.py' },
  { title: 'Step-by-step run tracing', body: 'Every node execution traces to LangSmith when LANGSMITH_TRACING and an API key are set. Off by default in this demo.', verifiedBy: 'tests/test_observability.py' },
];
